# Generated by Django 4.2.1 on 2023-06-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='content',
        ),
        migrations.AddField(
            model_name='subject',
            name='articl1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='articl2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='article_image1',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='article_image2',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='heading1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='heading2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
