# Generated by Django 4.2.1 on 2023-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_subject_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
