# Generated by Django 4.2.1 on 2023-06-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
