# Generated by Django 4.2.1 on 2023-06-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_tv',
            name='release_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_tv',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
