# Generated by Django 4.2.1 on 2023-06-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_movies_tv_release_date_alter_movies_tv_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('tasks', models.TextField()),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='movies_tv',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
