# Generated by Django 4.2 on 2023-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.IntegerField(auto_created=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_from',
            field=models.DateField(auto_now=True),
        ),
    ]
