# Generated by Django 4.2 on 2023-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0002_course_course_hours_course_end_at_course_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_hours',
            field=models.IntegerField(),
        ),
    ]
