# Generated by Django 4.2 on 2023-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0003_alter_course_course_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_from',
            field=models.DateField(auto_now_add=True),
        ),
    ]
