# Generated by Django 4.2 on 2023-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0004_alter_course_end_at_alter_course_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_from',
            field=models.DateField(),
        ),
    ]
