# Generated by Django 4.2 on 2023-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0005_alter_course_end_at_alter_course_start_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='presented_by',
            field=models.CharField(default='test', max_length=2084),
        ),
    ]
