# Generated by Django 4.2 on 2023-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0006_course_presented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='presented_by',
            field=models.CharField(max_length=2084),
        ),
    ]
