# Generated by Django 4.2 on 2023-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0007_alter_course_presented_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2084)),
                ('platform', models.CharField(max_length=2084)),
                ('about_project', models.TextField()),
                ('project_source', models.CharField(default='', max_length=2084)),
            ],
        ),
    ]
