# Generated by Django 4.2 on 2023-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
