# Generated by Django 4.2.1 on 2023-06-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=1048)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('type_of_inquery', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('file4', models.FileField(default='defaults/Doc1.pdf', upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('abstract', models.TextField()),
                ('file', models.FileField(default=None, upload_to='novels/')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('content', models.TextField()),
                ('file1', models.FileField(default=None, upload_to='comments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.novel')),
            ],
        ),
    ]
