# Generated by Django 4.2.1 on 2023-06-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file1',
        ),
    ]
