# Generated by Django 4.2.1 on 2023-06-06 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
