# Generated by Django 4.2.1 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_created_at_contact_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(),
        ),
    ]
