# Generated by Django 4.2.1 on 2023-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(default='Post')),
                ('date', models.DateField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(default='img/pinklogo.png', upload_to='img/')),
            ],
        ),
    ]
