# Generated by Django 4.2.1 on 2023-06-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_post1_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
