# Generated by Django 4.2.1 on 2023-06-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_postdigital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postanimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(default=5)),
                ('hour', models.IntegerField(default='5')),
                ('img', models.ImageField(default='img/pinklogo.png', upload_to='img/')),
            ],
        ),
    ]
