# Generated by Django 4.2.1 on 2023-06-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_postweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postanimal',
            name='size',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postdigital',
            name='size',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postweb',
            name='size',
            field=models.CharField(max_length=1000),
        ),
    ]
