# Generated by Django 4.2.1 on 2023-06-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_post_size_alter_postanimal_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post_digital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.postdigital'),
        ),
    ]
