# Generated by Django 4.2.1 on 2023-06-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_review_post_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post_digital',
        ),
    ]
