# Generated by Django 4.2.1 on 2023-06-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_review_post_digital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postanimal',
        ),
        migrations.DeleteModel(
            name='PostDigital',
        ),
        migrations.DeleteModel(
            name='Postweb',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Digital', 'Digital')], default='Manual', max_length=64),
            preserve_default=False,
        ),
    ]
