# Generated by Django 4.2.1 on 2023-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_delete_postanimal_delete_postdigital_delete_postweb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Digital', 'Digital'), ('Animal', 'Animal'), ('Web', 'Web')], max_length=64),
        ),
    ]
