# Generated by Django 4.2.1 on 2023-06-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('img', models.ImageField(default='img/pinklogo.png', upload_to='img/')),
            ],
        ),
    ]
