# Generated by Django 4.2.1 on 2023-06-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
