# Generated by Django 4.2.1 on 2023-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='images/'),
        ),
    ]
