# Generated by Django 4.2.1 on 2023-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_project_image_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_education', models.CharField(max_length=200)),
                ('description_education', models.TextField()),
                ('title_experience', models.CharField(max_length=200)),
                ('sub_title_experience', models.CharField(max_length=200)),
                ('description_experience', models.TextField()),
                ('title_skill', models.CharField(max_length=200)),
                ('percent_skill', models.CharField(max_length=200)),
                ('title_course', models.CharField(max_length=200)),
                ('name_course', models.CharField(max_length=200)),
            ],
        ),
    ]
