# Generated by Django 4.2.1 on 2023-06-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
