# Generated by Django 4.2.1 on 2023-06-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Blog',
        ),
    ]
