# Generated by Django 4.2.1 on 2023-06-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_game_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='game',
            new_name='blog',
        ),
    ]
