# Generated by Django 4.2.1 on 2023-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_courses_education_experience_skills_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='field_course',
            field=models.CharField(default='Computer security', max_length=200),
        ),
    ]
