# Generated by Django 4.2.1 on 2023-06-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_review"),
    ]

    operations = [
        migrations.DeleteModel(name="Review",),
    ]
